export type Detail = { id: string; title: string; purpose: string; what: string; why: string; how: string; pm: string; engineering: string; reconstructed?: boolean }
const detail = (id: string, title: string, purpose: string, what: string, how: string, pm: string, engineering: string, reconstructed = false): Detail => ({ id, title, purpose, what, why: purpose, how, pm, engineering, reconstructed })
export const nodes: Record<string, Detail> = Object.fromEntries([
  detail('query', 'User Query', '保留用户原始诉求，避免过早改写需求。', '本轮文本或语音转写输入。', '输入进入 Session；语音先经 ASR，随后进入语义处理。', '定义入口、用户场景与输入异常处理。', '接入输入通道、ASR 与事件记录。'),
  detail('session', 'Session State', '让连续服务记住当前任务和已知信息。', '一次连续服务中的消息记录与任务状态。', '区分 Message / Event Log 与 Task State，供每轮上下文选择使用。', '定义会话生命周期、可恢复任务及状态语义。', '实现 State Schema、持久化和失效处理。'),
  detail('context', 'Context Builder', '只给模型这一轮做判断所需的信息。', '从 Session 中筛选信息的上下文组装层。', '优先 Active Task、Current Agent、Slots / Entities，再补必要结果和近期相关原文。', '定义筛选优先级、摘要触发条件及预算目标。', '实现筛选、摘要、Token Counter 与截断策略。'),
  detail('rewrite', 'Query Rewrite · 按需', '补全省略与指代，同时守住用户需求边界。', '对原始表达进行上下文补全和语义规范。', '例如上一轮讨论咖啡店，本轮“怎么过去”引用已选商户；不凭空新增偏好。', '确定改写边界，整理口语、指代和错误改写的验收样例。', '实现改写 Prompt、模型调用及与原 Query 的关联记录。'),
  detail('routing', 'Routing Decision Node', '先确定任务关系与归属，防止把用户交给错误的业务能力。', '输出 Intent、Task Relation、Target Agent、Multi-intent 的决策层。', '结合本轮 Query 与 Session，交由 LangGraph 条件路由选择业务 Agent、多任务、澄清或兜底。', '定义意图体系、任务关系、业务规则和分流标准。', '实现分类 Prompt、输出校验与条件边。'),
  detail('business', 'Business Agent', '把“交给谁”与“如何完成”分开管理。', '按照业务目标、数据边界、执行流程划分的任务执行单元。', '设施、商业、文旅、交通 Agent 分别检查参数、调用能力并处理结果。', '定义 Agent 边界、任务完成标准和兜底。', '实现 Agent 节点、能力接入及执行流程。'),
  detail('slots', 'Slot / Task State', '能自动获取的参数，不重复问用户。', '任务所需参数及其执行状态。', '从 Query、Session、Location / Tool、用户点击或选择填槽；必要参数缺失才澄清。', '定义 Required Slot、来源优先级、补槽与失效规则。', '实现实体提取、参数校验、状态更新与恢复。'),
  detail('sources', 'RAG / Data / Tool', '让事实由合适的数据来源提供。', '知识检索、结构化查询和实时业务接口。', '稳定 FAQ 走 RAG，设施商户查结构化数据，网约车和动态交通调用 Tool。', '划分信息时效边界、来源优先级与失败策略。', '接入向量检索、数据库和业务 API。'),
  detail('result', 'Result Processing', '把可执行结果交给用户，减少模型不必要的加工。', '对检索或工具结果进行校验、筛选、排序和展示分配。', '程序处理距离和营业状态；完整商户字段直接交前端卡片，LLM 接收最小充分信息。', '定义排序、过滤、字段展示和异常提示规则。', '实现确定性处理、结果映射与数据校验。'),
  detail('response', 'Text + Card + Action', '在一次交互里给足做决定和下一步行动的信息。', '文字解释、结构化卡片和操作按钮组成的输出。', '商户列表同时显示距离、营业状态、位置与导航入口。', '设计信息层级、点击行为及导航失败体验。', '渲染卡片、绑定动作并同步用户选择。'),
  detail('update', 'Update Session', '让“这家”“继续”等下一轮表达有明确依据。', '将本轮事件、任务状态和关键结果写回会话。', '记录已选实体、key_result 和任务状态；下一轮由 Context Builder 决定读取哪些内容。', '定义保留内容、完成与取消语义。', '实现原子更新、存储与并发一致性处理。'),
  detail('feedback', 'Bad Case Feedback', '把失败变成可重复验证的改进。', '从错误问询回流到测试和规则的反馈机制。', '识别根因，调整数据 / Prompt / 意图边界 / Rewrite，再回归验证。', '归类问题、明确优先级与验收标准。', '提供日志、观测能力与回归执行支持。'),
  detail('facility', '设施服务 Agent', '公共服务优先，让基础需求最短路径得到满足。', '处理卫生间、免费饮水、母婴室和服务台等设施需求。', '查询设施数据，必要时通过共享 Location 和 Navigation 给出位置与路线。', '定义公共服务优先规则及定位失败的文字兜底。', '接入设施数据与共享定位导航能力。'),
  detail('commercial', '商业推荐 Agent', '把商户发现与实际到达衔接起来。', '处理餐饮、咖啡、购物、酒店 / 商业服务。', '按品类与位置查询商户，程序排序后输出商户卡片。', '定义推荐边界、展示字段和营业状态规则。', '实现商户查询、排序与卡片数据返回。'),
  detail('tourism', '文旅 Agent', '在旅客时间约束下提供可执行的游玩方案。', '处理景点、行程规划与旅游服务协作。', '结合高德 POI / 路线，必要时 A2A 调用杭州文旅 Agent「杭小忆」。', '定义跨 Agent 服务范围、信息传递与结果验收。', '实现高德接口、A2A 协作及结果处理。'),
  detail('transport', '交通出行 Agent', '让离站与换乘决策建立在有效的交通信息上。', '处理网约车、动态交通、车次和交通衔接。', '根据车牌号、车次等必要实体调用实时工具；不可用时明确说明。', '定义补槽、时效标识与无法查询时的反馈。', '实现交通 API、实体校验与异常返回。'),
  detail('location', 'Location', '用室内位置支持“附近”和“怎么走”。', '提供用户当前站内位置的共享能力。', 'GPS 室内不稳定，业务结合室内定位；权限失败尝试重新获取，最终文字兜底。', '定义授权时机、位置使用场景和失败体验。', '接入室内定位、权限状态与位置更新。'),
  detail('navigation', 'Navigation', '让所有业务复用到达能力，避免重复建设。', '共享能力，不是一级业务 Agent。', '接收起点和终点，商户点击导航也可提供终点；普通 POI 失败用文字，检票口 / 交通出站用图文指南。', '定义入口、起终点来源和不同目标的降级策略。', '实现路线能力、导航动作和结果展示。'),
  detail('rag', 'RAG', '用稳定知识支持回答，降低无依据生成。', '先检索再生成的知识增强链路。', 'Query → Qwen-Embedding → Vector Search → TopK → 必要时 Rerank → Context → Generation Model。', '定义知识范围、更新责任、召回验收及无依据时的处理。', '实现知识索引、召回与生成集成。'),
  detail('structured', 'Structured Data Query', '把设施和商户的属性交给可校验的数据查询。', '对结构化实体字段的检索与筛选。', '按品类、位置等条件找商户 / 设施；距离排序和状态过滤由程序完成。', '定义实体字段、筛选口径与卡片展示需求。', '实现查询、字段清洗、排序和数据同步。'),
  detail('tool', 'Tool Calling', '让实时事实来自业务系统。', '用明确参数调用业务 API 的执行能力。', '补齐车牌或车次后查询网约车 / 动态交通，错误或超时返回明确状态。', '定义 Tool 使用边界、参数约束与失败文案。', '实现 API 集成、日志、重试与结果校验。'),
  detail('intent', 'Intent', '明确用户想完成的业务目标。', '对本轮诉求的业务语义分类。', '“咖啡店查询”“餐厅推荐”都映射商业推荐能力，避免按表面问法拆 Agent。', '定义 Intent Definition、正反例与边界规则。', '实现分类与结构化输出校验。'),
  detail('relation', 'Task Relation', '在转话题和继续任务之间保持连贯。', '当前 Query 与已有任务的关系。', 'Continue 继续；New 新建；Switch 切换；Resume 恢复；Cancel 取消。具体判定与恢复策略按业务定义落地。', '定义状态语义、切换与取消行为，准备多轮测试样例。', '实现状态流转、条件判断与会话更新。'),
  detail('target', 'Target Agent', '让任务进入正确的数据与执行边界。', '路由输出的目标业务 Agent。', '选择设施、商业、文旅或交通；不确定时澄清或兜底。', '定义业务职责和跨边界优先规则。', '实现目标映射与路由跳转。'),
  detail('multi', 'Multi-intent', '只把独立目标拆成多任务。', '判断一轮请求是否含多个独立业务任务。', '文旅规划 + 返程查询拆任务；咖啡推荐 + 导航仍由商业 Agent 使用共享能力完成。', '定义独立任务判据、依赖关系与聚合规则。', '实现任务分发、依赖调度和汇总。'),
  detail('langgraph', 'LangGraph Conditional Routing', '把业务决策落实为可控的执行路径。', 'LangGraph 的条件路由机制；框架真实使用，具体节点实现为架构重建。', '按经过校验的路由结果进入 Business Agent / Multi-Agent / Clarification / Fallback。', '定义条件、分支结果和异常分支。', '实现具体节点、条件边和状态传递。', true),
  detail('clarify', 'Clarification', '只问会影响任务完成的必要问题。', '对意图不明确或必要参数不足的主动澄清。', '路由不确定时确认目标；业务 Agent 内缺槽时补充参数。', '定义何时问、问什么，以及最短追问方式。', '实现澄清响应和续接任务。'),
  detail('fallback', 'Fallback', '能力失败后仍提供诚实且有用的下一步。', '定位、工具或理解异常时的替代路径。', '位置不可得提供文字地点；实时数据不可用明确说明；无法识别诉求时引导重新描述。', '按场景定义降级、不可承诺内容和验收标准。', '实现异常检测、错误映射与降级分支。'),
  detail('log', 'Message / Event Log', '保留原始表达和用户动作以支持追溯。', '消息、点击与工具事件的记录。', '原文不全部进入模型；Context Builder 选择近期相关片段。', '定义需要记录的业务事件和使用范围。', '实现事件日志与关联查询。'),
  detail('task', 'Task State', '在多轮服务中保持任务身份与进度。', '任务级结构：task_id、intent、target_agent、status、slots / entities、key_result。', '这是解释状态边界的概念结构，非已核验生产 State Schema。', '定义字段业务语义、状态变更和任务恢复规则。', '实现实际 State Schema、存储和更新。', true),
  detail('summary', 'Conversation Summary', '压缩较早但仍有价值的长内容。', '从历史对话提取的必要摘要。', '仅对较早、有价值且较长的内容摘要；失效和无关内容不因摘要而自动保留。', '定义摘要触发与关键事实保真要求。', '实现摘要生成、来源追溯与上下文整合。'),
  detail('embedding', 'Qwen-Embedding', '把语义相近的知识找出来。', '项目已确认使用的 Embedding 模型，只负责检索，不生成答案。', '将 Query 向量化，与知识向量比较，交由召回阶段返回候选片段。', '验收口语、同义词和场站词的召回效果。', '实现向量化、索引与模型接入。'),
  detail('vector', 'Vector Search', '从知识库定位候选依据。', '基于语义向量的相似度检索。', '查询向量与知识索引匹配，召回候选片段。', '定义覆盖率和错误召回的评价口径。', '配置索引、查询与检索结果。'),
  detail('topk', 'TopK', '控制候选知识量与噪声。', '召回阶段选取的候选片段集合。', '供后续必要的重排与上下文组装使用；页面不声称具体生产 K 值。', '权衡覆盖、噪声与延迟并定义验收。', '实现候选截取与参数配置。'),
  detail('rerank', 'Rerank · 必要时', '在候选过多或相关性不足时提升证据排序。', '对初次召回结果的相关性重排。', '按需使用，不声称每轮生产必经重排或具体模型已确认。', '确定适用场景与是否值得增加延迟。', '实现重排调用和可选分支。'),
  detail('generate', 'Generation Model', '把检索依据组织成用户能理解的答复。', '依据筛选后的 Context 生成语言。', '接收知识片段与业务约束；Embedding 不承担这一步。', '定义回答结构、事实边界和无依据时的反馈。', '实现生成模型接入与输出处理。'),
  detail('deterministic', 'Deterministic → Rule / DB / Tool', '让确定性任务保持可预测、可校验。', '适合规则、数据库或程序执行的工作。', '距离排序、营业状态过滤、参数校验、API 执行由程序处理。', '定义业务规则与异常输出。', '实现查询、规则计算和工具执行。'),
  detail('light', 'Light Semantic → 轻量 LLM', '为轻语义任务控制响应成本和延迟。', '处理改写、意图分类、实体提取的模型层。', 'Qwen2.5 / Qwen3 仅作为合理补全的轻量模型选项，不是已确认生产模型。', '定义任务分层和准确率、延迟、成本的验收目标。', '按策略配置模型调用与条件分支。', true),
  detail('reasoning', 'Complex Reasoning → DeepSeek-R1', '为多条件决策提供推理能力。', '项目已确认使用 DeepSeek-R1；这里按任务复杂度解释调用策略。', '复杂问询、多条件判断、多 Agent、文旅规划与多 Tool 结果综合。', '定义复杂场景、策略边界及验收。', '通过 LangGraph 条件分支实现模型调用。'),
  detail('harness', 'Model + Harness', '让模型置于业务规则、状态和反馈约束中运行。', '模型周围的上下文、状态、工具、知识、规则、持久化与评测机制。', '回头看，这套架构天然体现了类似 Harness Engineering 的思想；不宣称项目当时采用这一方法论命名。', '定义业务 Harness：边界、状态、补槽、规则、兜底和验收。', '用 LangGraph 状态、节点、条件分支和持久化等骨架工程化实现。'),
  detail('rules', 'Business Rules', '让公共服务价值进入决策，而非只依赖语义相似度。', '业务方定义的服务优先级和约束。', '“哪里有水”优先免费饮水；“哪里可以买水”进入商业推荐，并可提示免费饮水设施。', '把公共服务优先转成路由规则和正反例。', '实现优先规则及对应回归验证。'),
  detail('aggregate', 'Response Aggregation', '给用户一个一致且可执行的答案。', '综合多个任务的结果与约束。', '交通时间必要时反向约束文旅行程；缺少返程信息先补槽，避免虚构可行性。', '定义冲突处理、结果次序及缺失信息提示。', '实现结果合并与依赖信息传递。'),
  detail('evaluation', 'Evaluation & Bad Case', '区分真实效果与可归因的改进证据。', '测试集评测、错误归因、迭代和上线回流。', '约 1000 条测试集测得意图准确率约 94.8%；9300+ 是首周有效问询量，不能作为准确率分母。', '设计测试集、错误分类、回归标准并推进修复。', '实现评测执行、日志采集与可观测性。'),
  detail('testset', 'Test Set', '用真实表达检验系统，而非只验证理想问法。', '约 1000 条意图识别测试样本。', '覆盖真实 Query、口语、同义表达与边界 Case；未提供的数据切分和标签分布不做虚构。', '组织标注口径、样本覆盖与验收。', '提供评测运行与结果导出。'),
  detail('rootcause', 'Root Cause Analysis', '找到错误发生层，避免所有问题都改 Prompt。', '按数据、Prompt、意图体系与改写等维度归因。', '区分不理解表达、边界冲突、缺失上下文和错误改写，再选择调整动作。', '判断根因并明确责任与验证样例。', '提供路由、检索和调用日志支持定位。'),
  detail('optimization', 'Data / Prompt / Intent / Rewrite', '用针对性的调整修复根因。', '四类互补的意图识别优化手段。', '补评测表达；修改定义 / 边界 / Few-shot；重划能力边界；按需补全省略和指代。', '选择优化方向，定义新旧样例验收口径。', '落实数据、Prompt、分类策略和改写流程变更。'),
  detail('regression', 'Regression Test', '确保修复一个问题没有引入相邻错误。', '调整后重跑已有和新增测试样例。', '同时检查相似意图、上下文切换和反例，再决定是否上线。', '定义通过标准、阻断问题与发布验收。', '实现批量评测、差异报告和版本关联。'),
  detail('production', 'Production', '把上线后的真实输入纳入持续改进。', '面对真实旅客的服务运行阶段。', '首周有效问询 9300+；新 Bad Case 回流到评测，不与离线准确率合并计算。', '关注场景扩展、体验问题和迭代优先级。', '负责日志、重试、部署和运行维护。'),
].map(item => [item.id, item]))

export const mainFlow = ['query', 'session', 'context', 'rewrite', 'routing', 'business', 'slots', 'sources', 'result', 'response', 'update', 'feedback']
export const slotRows = [
  ['设施查询', '设施类型；需要导航时的用户位置', 'Query + Location', '位置获取失败尝试重新授权', '最终用文字描述地点'],
  ['商业推荐', '品类；附近查询时的用户位置', 'Query + Location', '位置失败无法精确推荐距离', '展示文字位置'],
  ['网约车', '车牌号', '用户 Query / Session', '缺失则追问', '查不到提示确认车牌'],
  ['导航', '起点 + 终点', 'Location + Query / Session / 点击导航', '定位失败重新获取权限', '普通 POI 用文字；检票口 / 交通出站用图文指南'],
  ['动态交通', '车次等必要实体', 'Query / Session', '缺失则补槽', '实时数据不可用则明确说明'],
]
export const pmResponsibilities = ['用户需求与场景分析', 'MVP 范围', 'Agent 业务边界', 'Intent 体系', 'Routing 业务规则', 'Session / Task 业务状态', 'Slot 与澄清策略', 'RAG / Structured Data / Tool 使用边界', 'Business Rule', 'Bad Case 分析', '测试集与验收', '跨研发 / 算法 / 设计推进']
export const engineeringResponsibilities = ['LangGraph 具体节点和条件边', 'Prompt 工程实现', 'State Schema', 'Session 持久化', '模型 API 调用', 'Tool / API 集成', 'Token Counter', '日志 / 重试 / 部署']
