import { Alert, Button, Card, Col, Form, Modal, Progress, Radio, Row, Select, Space, Steps, Table, Tag } from 'antd'
import { AudioOutlined, PlusOutlined, RocketOutlined } from '@ant-design/icons'
import { useState } from 'react'
import { useDemo } from '../../store/DemoStore'
import { TaskStatusTag,taskMap } from '../components/StatusTag'
import type { TaskStatus } from '../../types/demo'

const sequence:TaskStatus[]=['CREATED','DISPATCHED','MOVING_TO_MEETING_POINT','WAITING_FOR_USER','MATCH_SUCCESS','LUGGAGE_CONFIRM','SERVING','COMPLETED']
export function Tasks() {
  const demo=useDemo();const [open,setOpen]=useState(false);const [form]=Form.useForm()
  const task=demo.activeTask, step=task?Math.max(0,sequence.indexOf(task.status)):0
  const create=()=>form.validateFields().then(v=>{demo.createTask(v);setOpen(false);form.resetFields()})
  return <div className="demo-page"><div className="page-heading"><div><h1>任务调度中心</h1><p>创建、派发并模拟机器人服务任务的完整状态机</p></div><Space><Button icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>创建任务</Button><Button type="primary" icon={<RocketOutlined/>} loading={demo.demoRunning} onClick={demo.startTaskDemo}>启动演示</Button></Space></div>
    <Alert type="info" showIcon message="自动汇合规则" description="持续获取机器人位置和用户位置；距离 > 10m 继续汇合，距离 ≤ 10m 自动进入 MATCH_SUCCESS。不使用预约码。"/>
    {task?<Row gutter={[16,16]} className="task-simulator"><Col xs={24} xl={16}><Card title={`当前任务 · ${task.id}`} extra={<TaskStatusTag status={task.status}/>}><Steps size="small" current={step} items={sequence.map(s=>({title:taskMap[s]}))}/><div className="task-live"><div><span>服务类型</span><b>{task.type}</b></div><div><span>执行机器人</span><b>{task.robot}</b></div><div><span>汇合点</span><b>{task.meetingPoint}</b></div><div><span>目的地</span><b>{task.destination}</b></div></div>
      {typeof task.distance==='number'&&<div className={`distance-panel ${task.distance<=10?'distance-panel--success':''}`}><span>机器人与用户距离</span><strong>{task.distance}<small>m</small></strong><Progress percent={Math.max(0,100-task.distance*3)} showInfo={false}/><p>{task.distance<=10?'距离 ≤ 10m，系统已自动判定汇合成功':'持续获取双方位置，继续显示汇合中'}</p></div>}
      {['MATCH_SUCCESS','LUGGAGE_CONFIRM'].includes(task.status)&&<div className="tts-panel"><AudioOutlined/><div><b>汇合成功</b><p>🔊 已汇合成功，是否需要放置行李？</p><Space><Button type={task.luggage===true?'primary':'default'} onClick={()=>demo.chooseLuggage(true)}>需要放置行李</Button><Button type={task.luggage===false?'primary':'default'} onClick={()=>demo.chooseLuggage(false)}>无需放置行李</Button></Space>{typeof task.luggage==='boolean'&&<><p>{task.luggage?'请将行李放置完成后开始服务':'无需放置行李，可直接开始导航'}</p><Button type="primary" onClick={demo.startNavigation}>开始导航</Button></>}</div></div>}
      {['SERVING','PAUSED'].includes(task.status)&&<div className="service-actions"><Alert message={task.status==='PAUSED'?'服务已暂停':'服务中 · 正在前往目的地'} type={task.status==='PAUSED'?'warning':'success'} showIcon/><Space>{task.status==='SERVING'?<Button onClick={()=>demo.taskAction('pause')}>暂停</Button>:<Button type="primary" onClick={()=>demo.taskAction('resume')}>继续</Button>}<Button danger onClick={()=>demo.taskAction('end')}>提前结束</Button><Button type="primary" onClick={()=>demo.taskAction('complete')}>完成任务</Button></Space></div>}
      </Card></Col><Col xs={24} xl={8}><Card title="状态事件流"><div className="event-stream">{sequence.map((s,i)=><div className={i<=step?'done':''} key={s}><i/ ><span>{s}</span><b>{taskMap[s]}</b></div>)}</div></Card></Col></Row>:<Card className="empty-task"><RocketOutlined/><h3>暂无进行中的任务</h3><p>点击“启动演示”体验自动距离汇合与服务状态流转。</p></Card>}
    <Card title="任务记录" className="page-card"><Table rowKey="id" dataSource={demo.tasks} pagination={{pageSize:6}} columns={[{title:'任务 ID',dataIndex:'id'},{title:'类型',dataIndex:'type'},{title:'汇合点',dataIndex:'meetingPoint'},{title:'目的地',dataIndex:'destination'},{title:'机器人',dataIndex:'robot'},{title:'状态',dataIndex:'status',render:s=><TaskStatusTag status={s}/>},{title:'创建时间',dataIndex:'createdAt'}]}/></Card>
    <Modal title="创建任务" open={open} onCancel={()=>setOpen(false)} onOk={create} okText="创建任务"><Form form={form} layout="vertical" initialValues={{type:'行李辅助',robot:'自动分配'}}><Form.Item name="type" label="任务类型" rules={[{required:true}]}><Radio.Group optionType="button" options={['行李辅助','路线引导','定点播报']}/></Form.Item><Form.Item name="meetingPoint" label="汇合点" rules={[{required:true}]}><Select options={['出站到达口南2','出站到达口南3','出站到达口北3'].map(v=>({value:v}))}/></Form.Item><Form.Item name="destination" label="目的地" rules={[{required:true}]}><Select options={['出租车上车点','网约车候车区','地铁入口','停车场'].map(v=>({value:v}))}/></Form.Item><Form.Item name="robot" label="执行机器人" rules={[{required:true}]} extra="仅在线 + 空闲机器人可选"><Select options={[{value:'自动分配'},{value:'小东鸭1'},{value:'小东鸭2',disabled:true,label:'小东鸭2 · 定点服务中'},{value:'小东鸭3',disabled:true,label:'小东鸭3 · 充电中'}]}/></Form.Item></Form></Modal>
  </div>
}
